spring:
  datasource:
    url: jdbc:h2:file:./data/bm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
    driver-class-name: org.h2.Driver
    username: bm
    password: bmbmbm77
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      schema: classpath:schema.sql
