server:
  port: 8081
#  port: 54355
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
#    url: jdbc:h2:file:./data/bm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:sqlite:./bm.db
#    driver-class-name: org.h2.Driver
    driver-class-name: org.sqlite.JDBC
    username: bm
    password: bmbmbm77
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#  web:
#    resources:
#      cache:
#        period: 3600
#      chain:
#        cache: true
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true


file:
  upload-dir: uploads
  access-path: /files
  max-size: 5MB
myfeign:
  bmbrowser: http://127.0.0.1:54345
#  bmserver: http://119.45.130.167:6796
  bmserver: http://127.0.0.1:8082
